apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: hackathon-gateway
  namespace: hackathon

spec:

  gatewayClassName: nginx

  listeners:

    - name: http
      protocol: HTTP
      port: 80

      allowedRoutes:
        namespaces:
          from: Same

    - name: https
      protocol: HTTPS
      port: 443
      hostname: __GATEWAY_HOSTNAME__

      tls:
        mode: Terminate

        certificateRefs:
          - kind: Secret
            name: hackathon-tls

      allowedRoutes:
        namespaces:
          from: Same

